### ISSUE TITLE
Unable to add driver

### ISSUE THREAD

**Issue by marcheschi** [yogeshsd/lwr-maven#1]
Hi
Today I tried the q2r tomcat7, 
the interface starts but I do not see the administrator button or the "add driver" button you mention on the documentation.
I can log in and see the driver list bun nothing else.
When I try to change password for adminuser or try to create a new user, I receive this error:
Save of user 'undefined' Failed
Response = "Unable to save user 'admin'.". Status = 500
Best regards
Paolo

**Comment by yogeshsd** [comment]
Hello Paolo,

Can you please send me a screenshot of the page along with browser console output. ( Ex: On chrome running on windows, you need to press F12) and also CATALINA_BASE/logs/q2r.log file for my reference?

I shall have a look and get back to you.

Thanks
Yogesh

**Comment by marcheschi** [comment]
Hi I'm out of the office at the moment. I will send you all after the 16 of
August.
Thank you
Paolo

Il ven 27 lug 2018 19:17 Yogesh Deshpande <notifications@github.com> ha
scritto:

**Comment by yogeshsd** [comment]
Hello Paolo,

I hope you have resumed work.

Would it be possible for you to send the requested details?

Thanks
Yogesh

**Comment by yogeshsd** [comment]
Hello Paolo,

Do you have any update for me?

Thanks
Yogesh

**Comment by yogeshsd** [comment]
Hello Paolo,

Closing the issue due to lack of response.

If the issue persist, we can always create a new bug and work on it.

Thanks
Yogesh
