### ISSUE TITLE
Export to excel / CSV

### ISSUE THREAD

**Issue by thuanvan** [yogeshsd/lwr-maven#2]
Would like an option to export to Excel and CSV

**Comment by yogeshsd** [comment]
Hello All,

The support to export the report data as CSV and Excel ( CSV ) is available in the latest version. You can download the latest version from
Sourceforge : https://sourceforge.net/projects/query2report/
Git : https://github.com/yogeshsd/lwr-maven/tree/master/dist

I am closing this issue now.

Thanks
Yogesh

**Comment by alopezalos** [comment]
After some issues and interaction, export is working again.
