### ISSUE TITLE
Save report failed

### ISSUE THREAD

**Issue by alopezalos** [yogeshsd/lwr-maven#3]
Hi, 
We have a blocking issue saving reports that prevent us to use the q2r tool. 
The .json for the report is saved correctly, it is possible to create a graph and this is created and visualized correctly but it fails when trying to save the report with the new content widget inside.
It was working ok until the last deployment of q2r.
Attached is the q2r.log file.
Any feedback will be welcome.
[q2r.log](https://github.com/yogeshsd/lwr-maven/files/2554188/q2r.log)
Thanks!

**Comment by yogeshsd** [comment]
Hello Angel,

Is it possible for you to attach the screen recording when you reproduce the issue? Screencastify is a good plugin for chrome to record the screen. If recording is not possible, can you attach the snapshot of the screen with the error? Ensure that the browser network debugging and browser console is shown in the snapshot. 

I want to check if there are any errors reported by any of the javascript on the browser console. So if you can enable this while capturing the data it would be helpful.

On chrome refer to this document to show the console log
https://developers.google.com/web/tools/chrome-devtools/console/

Similarly, for network performance debugging. I wanted to check if backend rest API is getting called and it resulted in HTTP success or error. Refer to this document for checking.
https://developers.google.com/web/tools/chrome-devtools/network-performance/
 
I would also need the TOMCAT_HOME_DIR/logs/catalina.out file as well.

Thanks
Yogesh

**Comment by alopezalos** [comment]
Hi Yogesh, 

Attached screenshots. Looks like one of the services is not responding.

![01-saving_report_frame_ok](https://user-images.githubusercontent.com/44813604

/48084685-4886e200-e1f0-11e8-95f7-28787f30e4c3.PNG)
![02-including_widget_on_report_ok](https://user-images.githubusercontent.com/44813604/48084686-4886e200-e1f0-11e8-87ec-5ae7d18736ed.PNG)
![02-saving_report widget_ko_failed](https://user-images.githubusercontent.com/44813604/48084687-4886e200-e1f0-11e8-8e76-1e2610ce4ae0.PNG)
![03b-saving_report widget_ko_failed_console](https://user-images.githubusercontent.com/44813604/48084688-4886e200-e1f0-11e8-9b0b-72b34e288f41.PNG)
![03c-saving_report widget_ko_failed_console](https://user-images.githubusercontent.com/44813604/48084689-4886e200-e1f0-11e8-90fc-877ebeab8b1d.PNG)

Thanks!!

**Comment by yogeshsd** [comment]
Hello Angel,

Can you create me a test report and admin user, i shall try to save the test report? If its possible, can send the details to yogeshsd@gmail.com.

Thanks
Yogesh

**Comment by yogeshsd** [comment]
Hello,

The issue is now resolved. Kindly pick the latest distribution from https://sourceforge.net/projects/query2report/

Thanks
Yogesh
